#!/usr/bin/env python3
"""Regenerate THIRD-PARTY-NOTICES.txt.

Usage:
    python scripts/gen_third_party_notices.py
    python scripts/gen_third_party_notices.py --check    # non-zero if stale

Run it after bumping Qt (update QT_VERSION and FFMPEG_VERSION below) or the
QWindowKit submodule. The output is committed and shipped in the release zip
next to LICENSE. Adapted from MegaDirStat's script of the same name.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = "THIRD-PARTY-NOTICES.txt"
SOURCE_URL = "https://github.com/tackme31/ToyFoxx"
COPYRIGHT_LINE = "ToyFoxx  Copyright (c) 2026  Takumi Yamada (tackme31)"

# Pinned in CLAUDE.md's requirements. Kept as constants so that a Qt bump shows
# up as a reviewable line in `git diff`. FFMPEG_VERSION is the FFmpeg build that
# this Qt release ships (its SBOM, sbom/qtmultimedia-<ver>.spdx.json, names it).
QT_VERSION = "6.11.1"
FFMPEG_VERSION = "7.1.3"

QT_MINOR = ".".join(QT_VERSION.split(".")[:2])
QT_SOURCE_URL = f"https://download.qt.io/archive/qt/{QT_MINOR}/{QT_VERSION}/single/"

QT_NOTICE = f"""\
The Qt Toolkit is Copyright (C) 2026 The Qt Company Ltd. and other
contributors.
Contact: https://www.qt.io/licensing/

ToyFoxx uses the Qt Community Edition under the terms of the GNU Lesser
General Public License, version 3 (LGPLv3). Only Qt modules available under
that license are distributed; no GPL-only Qt module is included.

You may use, distribute and copy the Qt libraries used by this application
under the terms of the LGPLv3, whose full text is reproduced immediately
below, followed by the GPLv3 text it builds upon. The Qt libraries are the
official Qt {QT_VERSION} binary release for MSVC, unmodified, and are shipped as
separate dynamic libraries, so a recipient may replace them with a modified,
interface-compatible build. The corresponding sources are published by The Qt
Company at:
  {QT_SOURCE_URL}

Qt itself bundles certain third-party code that is licensed under separate
terms from their original authors, independent of the LGPL/GPL terms above.
The full list and texts of these components are published by The Qt Company
at:
  https://doc.qt.io/qt-6/licenses-used-in-qt.html

Qt is a trademark of The Qt Company Ltd. in Finland and/or other countries
worldwide.
"""

FFMPEG_NOTICE = f"""\
This software uses code of FFmpeg (https://ffmpeg.org/), licensed under the
GNU Lesser General Public License, version 2.1 or later (LGPLv2.1+), whose
full text is reproduced below.

The FFmpeg {FFMPEG_VERSION} libraries (avcodec, avformat, avutil, swresample,
swscale) are the prebuilt binaries that ship with Qt {QT_VERSION}'s FFmpeg
media backend, unmodified, and are shipped as separate dynamic libraries.
They are built without any GPL or LGPLv3-only component. The FFmpeg sources
are at:
  https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n{FFMPEG_VERSION}.tar.gz
and the scripts Qt builds them with are in the Qt Multimedia repository
(https://code.qt.io/cgit/qt/qtmultimedia.git, tag v{QT_VERSION}). Parts of
FFmpeg are available under other permissive licenses; those are listed at:
  https://doc.qt.io/qt-{QT_MINOR.split(".")[0]}/qtmultimedia-attribution-ffmpeg.html
"""

QWINDOWKIT_NOTICE = """\
Copyright (C) 2023-2024 Stdware Collections (https://www.github.com/stdware)
Copyright (C) 2021-2023 wangwenx190 (Yuhang Zhao)
Copyright (C) 2025-2027 Wing-summer (wingsummer)

QWindowKit is built from source and linked statically into ToyFoxx.exe,
unmodified. It is licensed under the Apache License, version 2.0:
"""

PREAMBLE = f"""\
ToyFoxx
Third-Party Software Notices and Information

{COPYRIGHT_LINE}

This application, ToyFoxx, is licensed under the MIT License. A copy of that
license is included in the file named "LICENSE" in the root of this
distribution, and the software is provided without warranty of any kind.

The complete source code of ToyFoxx, including the build instructions needed
to rebuild it, is available at
{SOURCE_URL}

ToyFoxx incorporates or links against third-party software components that
are subject to separate copyright and license terms, as detailed below.
Reproducing this file, unmodified, alongside the LICENSE file satisfies the
attribution requirements of those components.

This file is generated by scripts/gen_third_party_notices.py -- do not edit it
by hand.
"""

BANNER = "=" * 79
RULE = "-" * 79


def read_text(path: Path) -> str:
    """Normalize to LF and a single trailing newline so output is byte-stable
    regardless of how git checked the input out."""
    raw = path.read_text(encoding="utf-8", errors="replace")
    return raw.replace("\r\n", "\n").replace("\r", "\n").rstrip("\n") + "\n"


def qwindowkit_version() -> str:
    """The submodule is pinned to a release tag; read it rather than repeat it,
    so a submodule bump makes --check fail until the notices are regenerated."""
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT / "third_party/qwindowkit"), "describe", "--tags", "--exact-match"],
        capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit("error: third_party/qwindowkit is not checked out at a release tag")
    return result.stdout.strip()


def components() -> list[dict]:
    licenses = REPO_ROOT / "licenses"
    return [
        {
            "name": "Qt",
            "version": QT_VERSION,
            "license": "LGPL-3.0-only",
            "homepage": "https://www.qt.io/",
            # LGPLv3 is written as additional permissions on top of GPLv3, so both texts travel.
            "text": "\n".join([QT_NOTICE, RULE, read_text(licenses / "LGPL-3.0.txt"),
                               RULE, read_text(licenses / "GPL-3.0.txt")]),
        },
        {
            "name": "FFmpeg",
            "version": FFMPEG_VERSION,
            "license": "LGPL-2.1-or-later",
            "homepage": "https://ffmpeg.org/",
            "text": "\n".join([FFMPEG_NOTICE, RULE, read_text(licenses / "LGPL-2.1.txt")]),
        },
        {
            "name": "QWindowKit",
            "version": qwindowkit_version(),
            "license": "Apache-2.0",
            "homepage": "https://github.com/stdware/qwindowkit",
            "text": "\n".join([QWINDOWKIT_NOTICE,
                               read_text(REPO_ROOT / "third_party/qwindowkit/LICENSE")]),
        },
    ]


def render() -> str:
    items = components()
    parts = [PREAMBLE, "Components", RULE]
    parts += [f"  {c['name']} {c['version']}  ({c['license']})" for c in items]
    parts.append("")
    for c in items:
        parts += [BANNER, f"{c['name']} {c['version']}", f"License: {c['license']}",
                  f"Homepage: {c['homepage']}", BANNER, "", c["text"]]
    return "\n".join(parts).rstrip("\n") + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the committed file is stale")
    args = parser.parse_args()

    out = REPO_ROOT / OUTPUT
    text = render()
    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != text:
            print(f"{OUTPUT} is stale; run python scripts/gen_third_party_notices.py", file=sys.stderr)
            return 1
        print(f"{OUTPUT} is up to date")
        return 0
    out.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
