# FFmpeg for the A-B segment export (F-25), without vendoring anything.
#
# - Headers: FFmpeg's public headers, fetched at configure time. The tag must match the FFmpeg
#   that Qt's media backend ships (Qt 6.11.1: 7.1.3, see avformat_configuration() of its DLL).
# - Libraries: none of our own. We link against the av*/sw* DLLs Qt ships next to its own and
#   windeployqt deploys. Qt ships no import libraries for them, so they are generated here from
#   the DLLs' export tables.
# - The DLLs are delay-loaded. If a newer Qt ships another FFmpeg major (other DLL names), the app
#   still starts; SegmentExporter checks the DLLs are there and only the export is unavailable.
#
# Defines the interface target toyfoxx_ffmpeg.

include(FetchContent)

# GitHub's archive downloads in seconds; ffmpeg.org's tarball took minutes here.
FetchContent_Declare(ffmpeg_headers
    URL https://github.com/FFmpeg/FFmpeg/archive/refs/tags/n7.1.3.tar.gz
    URL_HASH SHA256=e0b04c4b43d7e6d67cb6710334fb513adf13ac860532f30e1d0ac4c231f232fb
    DOWNLOAD_EXTRACT_TIMESTAMP ON)
# FFmpeg has no CMakeLists.txt, so this only downloads and extracts.
FetchContent_MakeAvailable(ffmpeg_headers)

# Only the public headers of the libraries in use, copied out of the source tree: with the tree
# itself on the include path, its top-level VERSION file would shadow C++20's <version> on a
# case-insensitive file system.
set(_ffmpeg_include_dir "${CMAKE_BINARY_DIR}/ffmpeg/include")
set(_ffmpeg_libs avformat avcodec avutil swscale swresample)
foreach(_lib IN LISTS _ffmpeg_libs)
    file(COPY "${ffmpeg_headers_SOURCE_DIR}/lib${_lib}" DESTINATION "${_ffmpeg_include_dir}"
        FILES_MATCHING PATTERN "*.h")
endforeach()
# Generated by FFmpeg's configure; these are the values for x64.
configure_file("${CMAKE_CURRENT_LIST_DIR}/ffmpeg/avconfig.h"
    "${_ffmpeg_include_dir}/libavutil/avconfig.h" COPYONLY)

get_target_property(_qmake Qt6::qmake IMPORTED_LOCATION)
get_filename_component(_qt_bin_dir "${_qmake}" DIRECTORY)
get_filename_component(_msvc_bin_dir "${CMAKE_CXX_COMPILER}" DIRECTORY)
find_program(TOYFOXX_DUMPBIN dumpbin HINTS "${_msvc_bin_dir}" REQUIRED)
find_program(TOYFOXX_LIB_EXE lib HINTS "${_msvc_bin_dir}" REQUIRED)

add_library(toyfoxx_ffmpeg INTERFACE)
target_include_directories(toyfoxx_ffmpeg SYSTEM INTERFACE "${_ffmpeg_include_dir}")

set(_ffmpeg_lib_dir "${CMAKE_BINARY_DIR}/ffmpeg/lib")
file(MAKE_DIRECTORY "${_ffmpeg_lib_dir}")
foreach(_lib IN LISTS _ffmpeg_libs)
    string(TOUPPER "${_lib}" _upper)
    # libavutil keeps it in version.h, the others in version_major.h.
    file(STRINGS "${_ffmpeg_include_dir}/lib${_lib}/version.h" _major_line
        REGEX "^#define LIB${_upper}_VERSION_MAJOR +[0-9]+")
    if(NOT _major_line)
        file(STRINGS "${_ffmpeg_include_dir}/lib${_lib}/version_major.h" _major_line
            REGEX "^#define LIB${_upper}_VERSION_MAJOR +[0-9]+")
    endif()
    string(REGEX REPLACE ".* ([0-9]+)$" "\\1" _major "${_major_line}")
    set(_dll "${_lib}-${_major}.dll")
    if(NOT EXISTS "${_qt_bin_dir}/${_dll}")
        message(FATAL_ERROR "${_dll} not found in ${_qt_bin_dir}. Qt's FFmpeg does not match the "
            "headers fetched in cmake/FFmpeg.cmake; move the tag to the FFmpeg this Qt ships.")
    endif()

    set(_def "${_ffmpeg_lib_dir}/${_lib}.def")
    set(_implib "${_ffmpeg_lib_dir}/${_lib}.lib")
    if("${_qt_bin_dir}/${_dll}" IS_NEWER_THAN "${_implib}")
        execute_process(COMMAND "${TOYFOXX_DUMPBIN}" /nologo /exports "${_qt_bin_dir}/${_dll}"
            OUTPUT_VARIABLE _exports COMMAND_ERROR_IS_FATAL ANY)
        # Rows of "ordinal hint RVA name".
        string(REGEX MATCHALL "\n +[0-9]+ +[0-9A-F]+ +[0-9A-F]+ +[A-Za-z_][A-Za-z0-9_]*" _rows "${_exports}")
        set(_content "LIBRARY ${_dll}\nEXPORTS\n")
        foreach(_row IN LISTS _rows)
            string(REGEX REPLACE ".* ([A-Za-z_][A-Za-z0-9_]*)$" "\\1" _name "${_row}")
            string(APPEND _content "    ${_name}\n")
        endforeach()
        file(WRITE "${_def}" "${_content}")
        execute_process(COMMAND "${TOYFOXX_LIB_EXE}" /nologo /machine:x64 "/def:${_def}" "/out:${_implib}"
            OUTPUT_QUIET COMMAND_ERROR_IS_FATAL ANY)
    endif()

    target_link_libraries(toyfoxx_ffmpeg INTERFACE "${_implib}")
    target_link_options(toyfoxx_ffmpeg INTERFACE "/DELAYLOAD:${_dll}")
endforeach()
target_link_libraries(toyfoxx_ffmpeg INTERFACE delayimp)
